---
title: "01-08-2023"
author: "David Will"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

## Dependencies

```{r}
if(!"pacman" %in% installed.packages()) install.packages("pacman")
pacman::p_load(here, tidyverse, tidytuesdayR, mapdata, sf, ggthemes, scales, plotly, lubridate, ggstream)
#options(scipen = 999)
```

## Import

```{r}
states_raw <- tt_load("2023-08-01")$states
etymology <- tt_load("2023-08-01")$state_name_etymology
```

Where do all the people live?

```{r}
mapdata <- map_data("state") %>% 
  st_as_sf(coords = c("long", "lat")) %>% 
  group_by(region) %>% 
  summarise(geometry = st_combine(geometry)) %>% 
  st_cast("POLYGON") %>% 
  mutate(region = str_to_title(region))

states <- states_raw %>% 
  full_join(mapdata, by = c("state" = "region")) %>% 
  filter(!state %in% c("Hawaii", "Alaska", "District Of Columbia")) %>% 
  st_as_sf()

states %>% 
  arrange(desc(population_2020))

states %>%
  ggplot() +
  geom_sf(aes(fill = population_2020)) + 
  scale_fill_binned(type = "viridis", 
                    labels = unit_format(unit = "M", scale = 1e-6)) +
  labs(title = "US states by population",
       legend = "") +
  theme_void() +
  theme(legend.position = "bottom",
        legend.title = element_blank())
```

Where are they packed?

```{r}
pop_density_scatter <- states %>%
  ggplot(aes(x = total_area_km2, y = population_2020, label = state)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "US states by population density",
       x = "Area in km2",
       y = "Population") +
  theme_light() +
  scale_x_continuous(labels = unit_format(unit = "K", scale = 1e-3)) +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6))

pop_density_scatter %>% 
  ggplotly()
```


Names seem to originate mostly from English, French and Spanish. Where there trends in union admission?

```{r}
# categorize and count
union <- states %>%
  as_tibble() %>% 
  left_join(etymology, by = "state") %>% 
  select(state, admission, language) %>%
  mutate(admission = year(admission),
         lang = str_extract(language, "(English|French|Spanish)(?! via)"),
         lang = ifelse(is.na(lang), "Other", lang)) %>%
  count(admission, lang)

# fill and sum
union_timeline <- union %>% 
  expand(admission = full_seq(admission, 1), lang) %>% 
  left_join(union) %>% 
  mutate(n = replace_na(n, 0),
         lang = fct_relevel(as_factor(lang), "English", "French", "Spanish", "Other")) %>% 
  group_by(lang) %>% 
  mutate(n_cum = cumsum(n)) %>% 
  ungroup()
  
# plot
ggplot(union_timeline, aes(x = admission, y = n_cum, fill = lang)) +
  geom_area() +
  scale_x_continuous(breaks = c(1800, 1820, 1840, 1860, 1880, 1900)) +
  coord_cartesian(expand = FALSE) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(title = "Origins of US State Names",
       x = "Admission to Union",
       y = "Count",
       caption = "Total count greater than 50 due to few states where names could originate from various languages.")
```

- bin names of native american descent?
- prettify (colors, labels, margins, font, highlight)
- pull in other data (welfare etc) & compare to admission date







```{r}
# Streamgraph provides wrong estimates?
ggplot(union_timeline, aes(x = admission, y = n_cum, fill = lang)) +
  geom_stream(true_range = "both") +
  scale_x_continuous(limits = c(1780, 1920),
                     breaks = c(1780, 1800, 1820, 1840, 1860, 1880, 1900, 1920)) +
  coord_cartesian(expand = FALSE)
```